import { expect, test } from '@playwright/test'
test.use({ actionTimeout: 12_000 })

test('procedural pistol has direct interaction, orbit and localized structure', async ({ page }, info) => {
  test.setTimeout(120_000)
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.goto('/?exhibit=russian-pistol-1798-1804')
  const stage = page.locator('.viewer-stage'), canvas = page.locator('canvas.viewer-canvas')
  await expect(stage).toHaveAttribute('data-state', 'ready', { timeout: 60_000 })
  await expect(page.locator('.hotspot-marker')).toHaveCount(0)
  await canvas.click({ position: { x: (await canvas.boundingBox())!.width / 2, y: (await canvas.boundingBox())!.height / 2 } })
  await expect(canvas).not.toHaveAttribute('data-selection', '')
  await page.getByRole('treeitem', { name: 'Ствол', exact: true }).click()
  await expect(canvas).toHaveAttribute('data-selection', 'entity:barrel')
  await expect(page.locator('.semantic-card')).toContainText('Укороченный ствол')
  const box = (await canvas.boundingBox())!
  await page.mouse.move(box.x + box.width * .7, box.y + box.height * .5)
  await page.mouse.down(); await page.mouse.move(box.x + box.width * .5, box.y + box.height * .5, { steps: 12 }); await page.mouse.move(box.x + box.width * .7, box.y + box.height * .5, { steps: 12 }); await page.mouse.up()
  await expect(canvas).toHaveAttribute('data-selection', 'entity:barrel')
  await expect(canvas).toHaveAttribute('data-orbit-changed', 'true')
  if (info.project.name === 'mobile') {
    const cdp = await page.context().newCDPSession(page)
    const x = box.x + box.width * .5, y = box.y + box.height * .5
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: x - 20, y, id: 1 }, { x: x + 20, y, id: 2 }] })
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x - 40, y, id: 1 }, { x: x + 40, y, id: 2 }] })
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    await expect(canvas).toHaveAttribute('data-selection', 'entity:barrel')
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y, id: 1 }] })
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchCancel', touchPoints: [] })
    await expect(canvas).toHaveAttribute('data-selection', 'entity:barrel')
    await cdp.detach()
  }
  await page.getByRole('button', { name: 'Сбросить ракурс', exact: true }).click()
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.getByRole('button', { name: 'Схема разборки', exact: true }).click()
  await expect(canvas).toHaveAttribute('data-assembly-animating', 'true')
  await expect(canvas).toHaveAttribute('data-assembly-animating', 'false')
  await page.getByRole('button', { name: 'Спусковой узел', exact: true }).click()
  await page.getByRole('button', { name: 'Раскрыть узел', exact: true }).click()
  await page.getByRole('button', { name: 'Собрать всё', exact: true }).click()
  await expect(canvas).toHaveAttribute('data-assembly-context', 'assembled')
  await expect(canvas).toHaveAttribute('data-assembly-animating', 'false')
  await page.getByRole('button', { name: 'Переключить язык' }).click()
  await expect(page.getByRole('tree', { name: 'Structure' })).toBeVisible()
  await page.screenshot({ path: `artifacts/pistol-direct-${info.project.name}.png` })
  expect(errors).toEqual([])
})
